//
// Created by vithurshan on 10/7/26.
//

#ifndef MUTUALEXCLUSION_DINING_PHILOSOPHER_H
#define MUTUALEXCLUSION_DINING_PHILOSOPHER_H

void diningPhilosopher();

#endif //MUTUALEXCLUSION_DINING_PHILOSOPHER_H
